### ISSUE TITLE
There is no AiticulatonBody 

### ISSUE THREAD

**Issue by springlight** [Unity-Technologies/articulations-robot-demo#16]
Hi I got this error

![image](https://user-images.githubusercontent.com/5945531/83114111-210da800-a0fb-11ea-86de-80ec064adda6.png)
![image](https://user-images.githubusercontent.com/5945531/83114126-27038900-a0fb-11ea-88c3-af60aebef734.png)

**Comment by sarahwolf32** [comment]
Make sure you are using the 2020.1 version of Unity.
