### ISSUE TITLE
Invalid AABB Articulations Solver Error 

### ISSUE THREAD

**Issue by nukadelic** [Unity-Technologies/articulations-robot-demo#2]
Arm part will break out when colliding table , the whole articulation body will break when doing more then 360 degrees turn of the 3rd wrist ( wrist3 - `M` button )

![i2HAXcDbpr](https://user-images.githubusercontent.com/6582633/76345190-783e8080-6335-11ea-939e-bd253334a555.gif)

Note : Failed to use 2020.1.0a25 due to invalid entitlement ( ? ) to some packages after clone , rolled back to 2020.1.0a17

 a17 Don't have this error, but before the downgrade from a25 after a fresh clone i was facing this issue on a fresh project clone:
```
Assets\Scripts\ArticulationJointController.cs(13,13): 
    error CS1069: The type name 'ArticulationBody' could not be found in the namespace 'UnityEngine'. 
    This type has been forwarded to assembly 'UnityEngine.PhysicsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Physics' in the Package Manager window to fix this error
```

**Edit** :
Did install the Physics package but still the same error is present in a25...
![image](https://user-images.githubusercontent.com/6582633/76346447-9efdb680-6337-11ea-8d41-2cf982c5c630.png)

Note i got a fresh a25 install via unity hub.

**Comment by sarahwolf32** [comment]
Nukadelic - thank you for writing up this detailed issue! This should be fixed now. Try pulling from master and running it in the latest beta. Please reach out if you find any remaining problems! :)

**Comment by dawood95** [comment]
Could you explain what the problem was? I am having a similar issue in my implementation. Thanks!
