### ISSUE TITLE
Nvidia's PhysX 4 implementation fro AMD GPUs ?

### ISSUE THREAD

**Issue by georgepoenaru** [Unity-Technologies/articulations-robot-demo#28]
Does the implementation of PhysX 4work also for AMD GPUs or Apple/ARM GPUs (iPhone, iPad)?

I'm especially interested in articulation joint system (available in 2020.1)  Temporal Gauss-Seidel (TGS)

**Comment by at669** [comment]
Hi @georgepoenaru, sorry for the delayed reply! I asked the Physics team, and this is their response:

> Our current integration only exposes the CPU path, and as such, runs on any supported platform regardless of the graphics chip. Potentially, PhysX has an optional feature to run physics on the GPU via CUDA or Compute. This is called GRB (=GPU rigid bodies), we don’t expose this yet in Unity.

Hope this answers your question!

**Comment by georgepoenaru** [comment]
Thank you @at669.
