### ISSUE TITLE
MLAgents GameObject not found

### ISSUE THREAD

**Issue by Ariansdf** [Unity-Technologies/articulations-robot-demo#30]
Hi,
I've just started with this project and followed every step correctly as I see. (ML Agents is installed and works fine in it's example project). However, as I've clone this project from github can't see any MLAgents GameObject in the scene to use the pre-trained model. 
Since I'm not going to work with machine learning/training and I'm trying to use this Project for other developments I don't want to train the arm again, but use the projects model.
I would be really thankful if you could help me through.

**Comment by Dueschen** [comment]
Hello Ariansdf,
Please check the mlagents branch to find the project with ML-Agents GameObject and pre-trained model.
Hope it helps!

**Comment by at669** [comment]
Hi @Ariansdf, the correct answer has been provided above. Please checkout the [mlagents](https://github.com/Unity-Technologies/articulations-robot-demo/tree/mlagents) branch of this repository for the ML-Agents usage. I will close out this ticket, but please feel free to open a new one if you have follow-up questions!
