### ISSUE TITLE
Get jointForce

### ISSUE THREAD

**Issue by freemind3r** [Unity-Technologies/articulations-robot-demo#32]
Hello. I am trying to read the joint force and for that I am using the following code:

public class PincherCollision : MonoBehaviour
{
   
    public ArticulationReducedSpace force;
    // Update is called once per frame
    void FixedUpdate()
    {
        ArticulationBody fingerA_articulation = GetComponent<ArticulationBody>();
        ArticulationReducedSpace force = fingerA_articulation.jointForce;
       
        Debug.Log("Force: ");
        Debug.Log(force);
    }
   
}
However I don't see any force being displayed and I'm not sure if I should convert the variable "force"to a different dataype. This is a script that I have attached to the FingerA object

**Comment by at669** [comment]
Hi @freemind3r! You will have to index into the `ArticulationReducedSpace force` value to get a reading, e.g. 

```csharp
ArticulationBody fingerA_articulation = GetComponent<ArticulationBody>();
ArticulationReducedSpace force = fingerA_articulation.jointForce;
   
Debug.Log($"Force: {force[0]}");
```

You can find more information in the [ArticulationReducedSpace Scripting documentation](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/ArticulationReducedSpace.html). Hope this helps!

**Comment by at669** [comment]
I will be closing this ticket due to inactivity. Please feel free to reopen it if the problem persists.
