### ISSUE TITLE
Extra joint in UR3e

### ISSUE THREAD

**Issue by jr-b-reiterer** [Unity-Technologies/articulations-robot-demo#33]
Hello, thanks for the great demos!

I think your UR3e model has an extra joint that does not exist in real UR robots. Comparing with actual UR robots, including UR3e (see, e.g., [this UR brochure](https://www.universal-robots.com/media/1802432/e-series-brochure.pdf)):
1. base - ok
2. shoulder - ok
3. elbow - ok
4. wrist1 - does not exist
5. wrist2 - should be wrist1
6. wrist3 - should be wrist2
7. "rotate hand" - should be wrist3 (as a small extra part between UR3e and gripper - it's not the (exchangeable) gripper that rotates on its own but the last robot link that it is attached to)

Is this difference intentional? 
If the model was closer to reality, that would be valuable as a reference for projects showing industrial scenes.

Kind regards
Bernhard

**Comment by at669** [comment]
Hey @jr-b-reiterer! This repository was primarily created to exhibit the ArticulationBody component and the TGS solver and excludes some of our other package functionalities. You may be interested in checking out our [URDF Importer](https://github.com/Unity-Technologies/URDF-Importer/) instead, which can define the correct geometry, visual meshes, kinematic and dynamic attributes of the robot in a Unity scene based on an imported URDF. You may also be interested in checking out our [Robotics Object Pose Estimation](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation) project, which has a UR3 arm imported via the URDF Importer.

**Comment by jr-b-reiterer** [comment]
Hello @at669, thanks for your reply!

Indeed, recently I have grown more accustomed to the URDF Importer, and I can obtain models that are "more true to original" quite well with it.

Regarding the importer, I was irritated by the single-material result obtained for many common URDF models (also affecting the pose estimation project you linked to), but it can be worked around, knowing the base issue described [here](https://github.com/siemens/ros-sharp/issues/133).

I understand there is limited interest on your side in changing the mismatch in this demo. I might try it myself in a fork when time allows it.

Thanks again!

**Comment by at669** [comment]
Glad to hear the URDF importer is working better for you! If you do try out more with this demo, feel free to keep us updated on it--I'll close out this ticket for now, but feel free to open a new one. Thanks!
