### ISSUE TITLE
Missing script on Cube object

### ISSUE THREAD

**Issue by BeardedVagabond** [Unity-Technologies/articulations-robot-demo#9]
Interesting repo! Excited to see Unity diving into robotics applications 😄 

My scene appears to be missing a script on the cube object? Is this a required script? 
Additionally, I'm finding it impossible to grasp the cube unless I drastically reduce it's mass (default is 200?). Is this related to the missing script? Or a parameter tuning thing? I've noticed the joint parameters seem very large when compared to real world values (e.g. maximum force of 3.4E38 is terrifying in the real world)

![image](https://user-images.githubusercontent.com/39106594/78867330-e2a12880-7a7b-11ea-8758-5c684fbfbcb2.png)

**Comment by PauliusSasnauskas** [comment]
@BeardedVagabond have you solved the grasping of the cube issue? Would you like to share your solution?
